/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './App.tsx',
    './main.tsx',
    './components/**/*.{ts,tsx}',
    './layouts/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
    './routes/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        secondary: '#006b5f',
        'secondary-fixed': '#71f8e4',
        'on-surface': '#191c1e',
        'on-primary-fixed-variant': '#003ea8',
        'tertiary-fixed': '#eaddff',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#d2bbff',
        'surface-container': '#eceef0',
        'surface-bright': '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-fixed': '#25005a',
        'on-primary-container': '#eeefff',
        'inverse-surface': '#2d3133',
        'primary-container': '#2563eb',
        'surface-dim': '#d8dadc',
        'inverse-primary': '#b4c5ff',
        'error-container': '#ffdad6',
        'outline-variant': '#c3c6d7',
        'on-secondary-fixed-variant': '#005048',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#00201c',
        'secondary-fixed-dim': '#4fdbc8',
        tertiary: '#6a1edb',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#f7edff',
        'secondary-container': '#6df5e1',
        outline: '#737686',
        surface: '#f7f9fb',
        'primary-fixed': '#dbe1ff',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#8343f4',
        'on-primary': '#ffffff',
        'surface-tint': '#0053db',
        'on-secondary-container': '#006f64',
        'on-primary-fixed': '#00174b',
        'surface-container-high': '#e6e8ea',
        background: '#f7f9fb',
        'on-error': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'on-surface-variant': '#434655',
        'on-background': '#191c1e',
        'on-tertiary-fixed-variant': '#5a00c6',
        'surface-variant': '#e0e3e5',
        primary: '#004ac6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-padding': '40px',
        unit: '8px',
        'section-gap': '64px',
        'card-padding': '32px',
      },
      fontFamily: {
        'headline-md': ['Poppins', 'sans-serif'],
        'headline-lg': ['Poppins', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Poppins', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        floating: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      animation: {
        floating: 'floating 6s ease-in-out infinite',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
